package edenrepo

import "time"

// StockTransferSingleResponse ...
type StockTransferSingleResponse struct {
	Status string `json:"status"`
	Data   struct {
		ID              string    `json:"id"`
		DocumentCode    string    `json:"document_code"`
		RecognitionDate time.Time `json:"recognition_date"`
		Origin          struct {
			ID   string `json:"id"`
			City struct {
				ID        string    `json:"id"`
				Value     string    `json:"value"`
				CityName  string    `json:"city_name"`
				CreatedAt time.Time `json:"created_at"`
				CreatedBy struct {
					ID          string `json:"id"`
					UsergroupID string `json:"usergroup_id"`
					Usergroup   struct {
						ID            string `json:"id"`
						UsergroupName string `json:"usergroup_name"`
						IsActive      int    `json:"is_active"`
					} `json:"usergroup"`
					Name       string      `json:"name"`
					Email      string      `json:"email"`
					Password   string      `json:"password"`
					IsActive   int         `json:"is_active"`
					LastLogin  time.Time   `json:"last_login"`
					PaperSize  string      `json:"paper_size"`
					Layout     string      `json:"layout"`
					MainOwner  interface{} `json:"main_owner"`
					Outlet     interface{} `json:"outlet"`
					OutletAll  interface{} `json:"outlet_all"`
					MainOutlet interface{} `json:"main_outlet"`
					Shift      interface{} `json:"shift"`
				} `json:"created_by"`
				CityCode     string `json:"city_code"`
				CustomerCode string `json:"customer_code"`
			} `json:"city"`
			WarehouseCode         string    `json:"warehouse_code"`
			WarehouseName         string    `json:"warehouse_name"`
			Note                  string    `json:"note"`
			IsDeleted             int       `json:"is_deleted"`
			Address               string    `json:"address"`
			PicName               string    `json:"pic_name"`
			PhoneNumber           string    `json:"phone_number"`
			AltPhoneNumber        string    `json:"alt_phone_number"`
			SubDistrictID         int       `json:"sub_district_id"`
			IsArchived            int       `json:"is_archived"`
			CreatedAt             time.Time `json:"created_at"`
			CreatedBy             int       `json:"created_by"`
			CreatedByName         string    `json:"created_by_name"`
			CreatedByEmail        string    `json:"created_by_email"`
			LastUpdatedAt         time.Time `json:"last_updated_at"`
			LastUpdatedBy         int       `json:"last_updated_by"`
			LastUpdatedByName     string    `json:"last_updated_by_name"`
			LastUpdatedByEmail    string    `json:"last_updated_by_email"`
			DeletedAt             time.Time `json:"deleted_at"`
			DeletedBy             int       `json:"deleted_by"`
			DeletedByName         string    `json:"deleted_by_name"`
			DeletedByEmail        string    `json:"deleted_by_email"`
			DeletionNote          string    `json:"deletion_note"`
			LastArchivedAt        time.Time `json:"last_archived_at"`
			LastArchivedBy        int       `json:"last_archived_by"`
			LastArchivedByName    string    `json:"last_archived_by_name"`
			LastArchivedByEmail   string    `json:"last_archived_by_email"`
			LastUnarchivedAt      time.Time `json:"last_unarchived_at"`
			LastUnarchivedBy      int       `json:"last_unarchived_by"`
			LastUnarchivedByName  string    `json:"last_unarchived_by_name"`
			LastUnarchivedByEmail string    `json:"last_unarchived_by_email"`
		} `json:"origin"`
		Destination struct {
			ID   string `json:"id"`
			City struct {
				ID        string    `json:"id"`
				Value     string    `json:"value"`
				CityName  string    `json:"city_name"`
				CreatedAt time.Time `json:"created_at"`
				CreatedBy struct {
					ID          string `json:"id"`
					UsergroupID string `json:"usergroup_id"`
					Usergroup   struct {
						ID            string `json:"id"`
						UsergroupName string `json:"usergroup_name"`
						IsActive      int    `json:"is_active"`
					} `json:"usergroup"`
					Name       string      `json:"name"`
					Email      string      `json:"email"`
					Password   string      `json:"password"`
					IsActive   int         `json:"is_active"`
					LastLogin  time.Time   `json:"last_login"`
					PaperSize  string      `json:"paper_size"`
					Layout     string      `json:"layout"`
					MainOwner  interface{} `json:"main_owner"`
					Outlet     interface{} `json:"outlet"`
					OutletAll  interface{} `json:"outlet_all"`
					MainOutlet interface{} `json:"main_outlet"`
					Shift      interface{} `json:"shift"`
				} `json:"created_by"`
				CityCode     string `json:"city_code"`
				CustomerCode string `json:"customer_code"`
			} `json:"city"`
			WarehouseCode         string    `json:"warehouse_code"`
			WarehouseName         string    `json:"warehouse_name"`
			Note                  string    `json:"note"`
			IsDeleted             int       `json:"is_deleted"`
			Address               string    `json:"address"`
			PicName               string    `json:"pic_name"`
			PhoneNumber           string    `json:"phone_number"`
			AltPhoneNumber        string    `json:"alt_phone_number"`
			SubDistrictID         int       `json:"sub_district_id"`
			IsArchived            int       `json:"is_archived"`
			CreatedAt             time.Time `json:"created_at"`
			CreatedBy             int       `json:"created_by"`
			CreatedByName         string    `json:"created_by_name"`
			CreatedByEmail        string    `json:"created_by_email"`
			LastUpdatedAt         time.Time `json:"last_updated_at"`
			LastUpdatedBy         int       `json:"last_updated_by"`
			LastUpdatedByName     string    `json:"last_updated_by_name"`
			LastUpdatedByEmail    string    `json:"last_updated_by_email"`
			DeletedAt             time.Time `json:"deleted_at"`
			DeletedBy             int       `json:"deleted_by"`
			DeletedByName         string    `json:"deleted_by_name"`
			DeletedByEmail        string    `json:"deleted_by_email"`
			DeletionNote          string    `json:"deletion_note"`
			LastArchivedAt        time.Time `json:"last_archived_at"`
			LastArchivedBy        int       `json:"last_archived_by"`
			LastArchivedByName    string    `json:"last_archived_by_name"`
			LastArchivedByEmail   string    `json:"last_archived_by_email"`
			LastUnarchivedAt      time.Time `json:"last_unarchived_at"`
			LastUnarchivedBy      int       `json:"last_unarchived_by"`
			LastUnarchivedByName  string    `json:"last_unarchived_by_name"`
			LastUnarchivedByEmail string    `json:"last_unarchived_by_email"`
		} `json:"destination"`
		DestinationAddress string    `json:"destination_address"`
		EtaDate            time.Time `json:"eta_date"`
		EtaTime            string    `json:"eta_time"`
		TotalWeight        float64   `json:"total_weight"`
		Note               string    `json:"note"`
		DocumentStatus     string    `json:"document_status"`
		CancellationNote   string    `json:"cancellation_note"`
		CreatedAt          time.Time `json:"created_at"`
		CreatedBy          int       `json:"created_by"`
		CreatedByName      string    `json:"created_by_name"`
		CreatedByEmail     string    `json:"created_by_email"`
		LastUpdatedAt      time.Time `json:"last_updated_at"`
		LastUpdatedBy      int       `json:"last_updated_by"`
		LastUpdatedByName  string    `json:"last_updated_by_name"`
		LastUpdatedByEmail string    `json:"last_updated_by_email"`
		CancelledAt        time.Time `json:"cancelled_at"`
		CancelledBy        int       `json:"cancelled_by"`
		CancelledByName    string    `json:"cancelled_by_name"`
		CancelledByEmail   string    `json:"cancelled_by_email"`
		ConfirmedAt        time.Time `json:"confirmed_at"`
		ConfirmedBy        int       `json:"confirmed_by"`
		ConfirmedByName    string    `json:"confirmed_by_name"`
		ConfirmedByEmail   string    `json:"confirmed_by_email"`
		TotalCost          int       `json:"total_cost"`
		StockTransferItems []struct {
			ID            string `json:"id"`
			StockTransfer struct {
				ID              string    `json:"id"`
				DocumentCode    string    `json:"document_code"`
				RecognitionDate time.Time `json:"recognition_date"`
				Origin          struct {
					ID   string `json:"id"`
					City struct {
						ID           string    `json:"id"`
						Value        string    `json:"value"`
						CityName     string    `json:"city_name"`
						CreatedAt    time.Time `json:"created_at"`
						CityCode     string    `json:"city_code"`
						CustomerCode string    `json:"customer_code"`
					} `json:"city"`
					WarehouseCode         string    `json:"warehouse_code"`
					WarehouseName         string    `json:"warehouse_name"`
					Note                  string    `json:"note"`
					IsDeleted             int       `json:"is_deleted"`
					Address               string    `json:"address"`
					PicName               string    `json:"pic_name"`
					PhoneNumber           string    `json:"phone_number"`
					AltPhoneNumber        string    `json:"alt_phone_number"`
					SubDistrictID         int       `json:"sub_district_id"`
					IsArchived            int       `json:"is_archived"`
					CreatedAt             time.Time `json:"created_at"`
					CreatedBy             int       `json:"created_by"`
					CreatedByName         string    `json:"created_by_name"`
					CreatedByEmail        string    `json:"created_by_email"`
					LastUpdatedAt         time.Time `json:"last_updated_at"`
					LastUpdatedBy         int       `json:"last_updated_by"`
					LastUpdatedByName     string    `json:"last_updated_by_name"`
					LastUpdatedByEmail    string    `json:"last_updated_by_email"`
					DeletedAt             time.Time `json:"deleted_at"`
					DeletedBy             int       `json:"deleted_by"`
					DeletedByName         string    `json:"deleted_by_name"`
					DeletedByEmail        string    `json:"deleted_by_email"`
					DeletionNote          string    `json:"deletion_note"`
					LastArchivedAt        time.Time `json:"last_archived_at"`
					LastArchivedBy        int       `json:"last_archived_by"`
					LastArchivedByName    string    `json:"last_archived_by_name"`
					LastArchivedByEmail   string    `json:"last_archived_by_email"`
					LastUnarchivedAt      time.Time `json:"last_unarchived_at"`
					LastUnarchivedBy      int       `json:"last_unarchived_by"`
					LastUnarchivedByName  string    `json:"last_unarchived_by_name"`
					LastUnarchivedByEmail string    `json:"last_unarchived_by_email"`
				} `json:"origin"`
				Destination struct {
					ID   string `json:"id"`
					City struct {
						ID           string    `json:"id"`
						Value        string    `json:"value"`
						CityName     string    `json:"city_name"`
						CreatedAt    time.Time `json:"created_at"`
						CityCode     string    `json:"city_code"`
						CustomerCode string    `json:"customer_code"`
					} `json:"city"`
					WarehouseCode         string    `json:"warehouse_code"`
					WarehouseName         string    `json:"warehouse_name"`
					Note                  string    `json:"note"`
					IsDeleted             int       `json:"is_deleted"`
					Address               string    `json:"address"`
					PicName               string    `json:"pic_name"`
					PhoneNumber           string    `json:"phone_number"`
					AltPhoneNumber        string    `json:"alt_phone_number"`
					SubDistrictID         int       `json:"sub_district_id"`
					IsArchived            int       `json:"is_archived"`
					CreatedAt             time.Time `json:"created_at"`
					CreatedBy             int       `json:"created_by"`
					CreatedByName         string    `json:"created_by_name"`
					CreatedByEmail        string    `json:"created_by_email"`
					LastUpdatedAt         time.Time `json:"last_updated_at"`
					LastUpdatedBy         int       `json:"last_updated_by"`
					LastUpdatedByName     string    `json:"last_updated_by_name"`
					LastUpdatedByEmail    string    `json:"last_updated_by_email"`
					DeletedAt             time.Time `json:"deleted_at"`
					DeletedBy             int       `json:"deleted_by"`
					DeletedByName         string    `json:"deleted_by_name"`
					DeletedByEmail        string    `json:"deleted_by_email"`
					DeletionNote          string    `json:"deletion_note"`
					LastArchivedAt        time.Time `json:"last_archived_at"`
					LastArchivedBy        int       `json:"last_archived_by"`
					LastArchivedByName    string    `json:"last_archived_by_name"`
					LastArchivedByEmail   string    `json:"last_archived_by_email"`
					LastUnarchivedAt      time.Time `json:"last_unarchived_at"`
					LastUnarchivedBy      int       `json:"last_unarchived_by"`
					LastUnarchivedByName  string    `json:"last_unarchived_by_name"`
					LastUnarchivedByEmail string    `json:"last_unarchived_by_email"`
				} `json:"destination"`
				DestinationAddress string    `json:"destination_address"`
				EtaDate            time.Time `json:"eta_date"`
				EtaTime            string    `json:"eta_time"`
				TotalWeight        float64   `json:"total_weight"`
				Note               string    `json:"note"`
				DocumentStatus     string    `json:"document_status"`
				CancellationNote   string    `json:"cancellation_note"`
				CreatedAt          time.Time `json:"created_at"`
				CreatedBy          int       `json:"created_by"`
				CreatedByName      string    `json:"created_by_name"`
				CreatedByEmail     string    `json:"created_by_email"`
				LastUpdatedAt      time.Time `json:"last_updated_at"`
				LastUpdatedBy      int       `json:"last_updated_by"`
				LastUpdatedByName  string    `json:"last_updated_by_name"`
				LastUpdatedByEmail string    `json:"last_updated_by_email"`
				CancelledAt        time.Time `json:"cancelled_at"`
				CancelledBy        int       `json:"cancelled_by"`
				CancelledByName    string    `json:"cancelled_by_name"`
				CancelledByEmail   string    `json:"cancelled_by_email"`
				ConfirmedAt        time.Time `json:"confirmed_at"`
				ConfirmedBy        int       `json:"confirmed_by"`
				ConfirmedByName    string    `json:"confirmed_by_name"`
				ConfirmedByEmail   string    `json:"confirmed_by_email"`
				TotalCost          int       `json:"total_cost"`
			} `json:"stock_transfer"`
			GroupID struct {
				ID                 string `json:"id"`
				LastUpdatedByID    string `json:"last_updated_by_id"`
				LastArchivedByID   string `json:"last_archived_by_id"`
				LastUnarchivedByID string `json:"last_unarchived_by_id"`
				ItemUomID          string `json:"item_uom_id"`
				CreatedByID        string `json:"created_by_id"`
				ItemUom            struct {
					ID               string    `json:"id"`
					MainOutletID     string    `json:"main_outlet_id"`
					ItemUomName      string    `json:"item_uom_name"`
					Note             string    `json:"note"`
					IsArchived       int       `json:"is_archived"`
					CreatedAt        time.Time `json:"created_at"`
					LastUpdatedAt    time.Time `json:"last_updated_at"`
					LastArchivedAt   time.Time `json:"last_archived_at"`
					LastUnarchivedAt time.Time `json:"last_unarchived_at"`
				} `json:"item_uom"`
				GroupCode      string    `json:"group_code"`
				GroupName      string    `json:"group_name"`
				AvailableStock int       `json:"available_stock"`
				MinimumStock   int       `json:"minimum_stock"`
				Note           string    `json:"note"`
				CreatedAt      time.Time `json:"created_at"`
				CreatedBy      struct {
					ID          string `json:"id"`
					UsergroupID string `json:"usergroup_id"`
					Usergroup   struct {
						ID            string `json:"id"`
						UsergroupName string `json:"usergroup_name"`
						IsActive      int    `json:"is_active"`
					} `json:"usergroup"`
					Name       string      `json:"name"`
					Email      string      `json:"email"`
					Password   string      `json:"password"`
					IsActive   int         `json:"is_active"`
					LastLogin  time.Time   `json:"last_login"`
					PaperSize  string      `json:"paper_size"`
					Layout     string      `json:"layout"`
					MainOwner  interface{} `json:"main_owner"`
					Outlet     interface{} `json:"outlet"`
					OutletAll  interface{} `json:"outlet_all"`
					MainOutlet interface{} `json:"main_outlet"`
					Shift      interface{} `json:"shift"`
				} `json:"created_by"`
				LastUpdatedAt    time.Time   `json:"last_updated_at"`
				LastUpdatedBy    interface{} `json:"last_updated_by"`
				LastArchivedAt   time.Time   `json:"last_archived_at"`
				LastArchivedBy   interface{} `json:"last_archived_by"`
				LastUnarchivedAt time.Time   `json:"last_unarchived_at"`
				LastUnarchivedBy interface{} `json:"last_unarchived_by"`
				IsArchived       int         `json:"is_archived"`
				CategoryTypeID   int         `json:"category_type_id"`
				IsDeleted        int         `json:"is_deleted"`
				DeletionNote     string      `json:"deletion_note"`
				DeletedAt        time.Time   `json:"deleted_at"`
				DeletedBy        int         `json:"deleted_by"`
				DeletedByName    string      `json:"deleted_by_name"`
				DeletedByEmail   string      `json:"deleted_by_email"`
			} `json:"group_id"`
			DeliverQty  int         `json:"deliver_qty"`
			ReceiveQty  int         `json:"receive_qty"`
			Weight      float64     `json:"weight"`
			UnitCost    int         `json:"unit_cost"`
			Subtotal    int         `json:"subtotal"`
			Note        string      `json:"note"`
			ReceiveNote string      `json:"receive_note"`
			User        interface{} `json:"user"`
		} `json:"stock_transfer_items"`
	} `json:"data"`
}
